import { ReactNode } from "react";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Directly define the function to accept children and any additional props
export default function RootLayout({ children, ...props }: { children: ReactNode; [key: string]: any }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition {...props}>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
